apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: evento
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: dockerhub-secrets
      containers:
      - name: frontend
        image: docker pull yatshhh/evento_frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: ""
        ports:
        - containerPort: 3000
