apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: evento
  labels: 
    role: backend
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: backend
        image: yatshhh/evento_backend
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: "mongodb+srv://cluster0admin:cluster0admin@cluster0.iq82tkg.mongodb.net/?retryWrites=true&w=majority"
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
          - name: JWT_SECRET_KEY
            value: "RFTGbuhijokCGVHBJjnk745623d84523wert84nrf8"
          
        ports:
        - containerPort: 5000
        livenessProbe: 
          httpGet:
            path: /ok
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 5000
            
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
