apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: evento
  labels: 
    role: api
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: yatshhh/evento_backend
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: JWT_SECRET_KEY
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: DB_URL
        ports:
        - containerPort: 8000
        livenessProbe: 
          httpGet:
            path: /ok
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
